name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Get Source
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
      - name: Run NPM Install
        run: npm ci
      - name: Verify Node and npm versions
        run: |
          echo "Node version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Architecture: $(node -p 'process.arch')"
      - name: Build
        run: npm run generate
      - name: Verify build output
        run: |
          echo "Build output structure:"
          ls -la .output/
          echo "Public directory contents:"
          ls -la .output/public/
          echo "Checking for required files:"
          test -f .output/public/index.html && echo "✓ index.html exists" || echo "✗ index.html missing"
          test -d .output/public/_nuxt && echo "✓ _nuxt directory exists" || echo "✗ _nuxt directory missing"
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          NODE_VERSION: '20.19.0'
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_SEA_04261F01E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: '.output/public' # Built app content directory - optional
          skip_app_build: true # Skip build since we're pre-building
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_SEA_04261F01E }}
          action: "close"



